[wokwi]
version = 1
firmware = "c_src/esp32_mesh/master_node/.pio/build/esp32dev/firmware.bin"
elf = "c_src/esp32_mesh/master_node/.pio/build/esp32dev/firmware.elf"

# Mở cổng Serial của 2 board qua cổng TCP mạng cục bộ
rfc2217ServerPort = 4000